del "*.suo" /S/Q/F/A
del "*.csproj.user" /S/Q/F/A
del "ld.web.demo\bin\*.pdb" /Q
rd "ld.web.demo\obj" /S/Q
rd "ld.web.demo\(logs)" /S/Q
rd "LanguageDetector\bin" /S/Q
rd "LanguageDetector\obj" /S/Q
rd "ld.model-builder.console\bin" /S/Q
rd "ld.model-builder.console\obj" /S/Q
rd "ld.model-converter-txt-2-bin.console\bin" /S/Q
rd "ld.model-converter-txt-2-bin.console\obj" /S/Q
rd "ld.TestApp\bin" /S/Q
rd "ld.TestApp\obj" /S/Q
